// Datos de los productos.
// Tu etiqueta de afiliado es: tiendanovedad-20
//
// PARA AGREGAR UN PRODUCTO:
// Copia un bloque completo (desde { hasta },), pégalo debajo del último
// y cambia los datos. Sube el número de "id" para que no se repita.
//
// CATEGORÍAS QUE USA LA WEB (escríbelas exactamente igual):
// "Electrónica" · "Hogar y Cocina" · "Oficina y Gaming" · "Deportes y Aire Libre"

window.PRODUCTS = [
  {
    id: 1,
    nombre: "Procesador AMD Ryzen 5 9600X, 6 núcleos y 12 hilos, desbloqueado",
    categoria: "Oficina y Gaming",
    precio: 173.00,
    precioOriginal: 279.00,
    imagen: "https://m.media-amazon.com/images/I/61piWP2l0GL._AC_SL1500_.jpg",
    urlAfiliado: "https://www.amazon.com/dp/B0D6NN6TM7?tag=tiendanovedad-20",
    badge: "Amazon's Choice",
    razon: "Arquitectura Zen 5 con 5,4 GHz y plataforma AM5, que admite DDR5 y PCIe 5.0. Al ser socket nuevo, permite cambiar solo el procesador dentro de unos años sin botar la placa.",
  },
  {
    id: 2,
    nombre: "Procesador Intel Core Ultra 5 225F, 10 núcleos (6P + 4E), hasta 4,9 GHz",
    categoria: "Oficina y Gaming",
    precio: 149.99,
    precioOriginal: 157.99,
    imagen: "https://m.media-amazon.com/images/I/616wIeBa-HL._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/4zAL2FI",
    badge: "",
    razon: "Reparte el trabajo entre núcleos de rendimiento y de eficiencia, así que rinde bien con varias aplicaciones abiertas a la vez. La terminación F significa que no trae video integrado: necesitas tarjeta gráfica aparte.",
  },
  {
    id: 3,
    nombre: "Memoria RAM Gigastone Game PRO 32 GB (2x16 GB) DDR4 3200 MHz CL16",
    categoria: "Oficina y Gaming",
    precio: 206.09,
    precioOriginal: 228.99,
    imagen: "https://m.media-amazon.com/images/I/51BM392zpdL._AC_SL1000_.jpg",
    urlAfiliado: "https://amzn.to/4xnaQDU",
    badge: "Amazon's Choice",
    razon: "Kit de dos módulos para trabajar en doble canal, con perfil XMP 2.0 que activa los 3200 MHz desde la BIOS sin configurar a mano. Verifica antes que tu placa sea DDR4, porque no es compatible con DDR5.",
  },
  {
    id: 4,
    nombre: "Teclado mecánico inalámbrico AULA F75 Pro, 75%, RGB, hot-swap",
    categoria: "Oficina y Gaming",
    precio: 69.99,
    precioOriginal: 79.99,
    imagen: "https://m.media-amazon.com/images/I/61MC8BK0w0L._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/4y3te4F",
    badge: "",
    razon: "Los interruptores se cambian sin soldar, así que puedes ajustar el tacto sin comprar otro teclado. Formato 75% que ahorra escritorio, con tres modos de conexión: cable, 2,4 GHz y Bluetooth.",
  },
  {
    id: 5,
    nombre: "Mouse gamer inalámbrico Razer Viper V3 Pro, 54 g, 8000 Hz",
    categoria: "Oficina y Gaming",
    precio: 119.99,
    precioOriginal: 159.99,
    imagen: "https://m.media-amazon.com/images/I/61BJ2MpgTTL._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/45KAQNb",
    badge: "Amazon's Choice",
    razon: "54 gramos y 95 horas de batería: la ligereza se nota en sesiones largas, y no depende de estar cargándolo cada día. Sensor de 35.000 DPI e interruptores ópticos, que no sufren el doble clic de los mecánicos.",
  },
  {
    id: 6,
    nombre: "Monitor portátil AOC 16T20 de 15,6\" FHD, USB-C, IPS ultradelgado",
    categoria: "Electrónica",
    precio: 59.99,
    precioOriginal: 69.99,
    imagen: "https://m.media-amazon.com/images/I/61mqQ3Qp2DL._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/4xjGP7Z",
    badge: "Amazon's Choice",
    razon: "Segunda pantalla que se conecta con un solo cable USB-C y pesa poco. A este precio es la forma más barata de trabajar con dos pantallas fuera del escritorio.",
  },
  {
    id: 7,
    nombre: "Monitor portátil ASUS ZenScreen MB16AHV de 15,6\" 1080p con funda",
    categoria: "Electrónica",
    precio: 141.12,
    precioOriginal: 149.00,
    imagen: "https://m.media-amazon.com/images/I/614tktFtFZL._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/4ghJV6o",
    badge: "Amazon's Choice",
    razon: "Trae soporte plegable, funda protectora y filtro de luz azul, pensado para moverlo a diario. Cuesta más que otros portátiles, pero el acabado y el soporte propio se notan si vas a viajar con él.",
  },
  {
    id: 8,
    nombre: "Memorias USB 3.0 PNY Turbo Attaché 3 de 128 GB, paquete de 5",
    categoria: "Electrónica",
    precio: 59.99,
    precioOriginal: 74.99,
    imagen: "https://m.media-amazon.com/images/I/6155RbbYkAL._AC_SL1000_.jpg",
    urlAfiliado: "https://amzn.to/4wPbk4h",
    badge: "Amazon's Choice",
    razon: "Sale a 12 dólares cada una por 128 GB con USB 3.0, muy por debajo del precio unitario local. El collar deslizante evita perder la tapa, que es como terminan la mayoría.",
  },
  {
    id: 9,
    nombre: "Memorias USB 2.0 PNY Attaché 3 de 16 GB, paquete de 10",
    categoria: "Electrónica",
    precio: 49.99,
    precioOriginal: 62.99,
    imagen: "https://m.media-amazon.com/images/I/812b8wIcqWL._AC_SL1500_.jpg",
    urlAfiliado: "https://amzn.to/4qAGhrC",
    badge: "Amazon's Choice",
    razon: "Diez unidades para repartir entre trabajo, clases y respaldos sueltos. Son USB 2.0, así que sirven para documentos, no para mover archivos pesados.",
  },
    ];
